# Generated by Django 4.1.5 on 2023-01-10 19:46

import django.core.validators
from django.db import migrations, models
import productsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0002_product_color_product_slug_alter_product_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=productsapi.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
