# Generated by Django 4.1.5 on 2023-01-12 14:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0003_remove_product_subcategory_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
