# Generated by Django 4.1.5 on 2023-01-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0006_order_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, null=True)),
                ('size', models.FloatField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='productsapi.orderitem'),
        ),
    ]
