# Generated by Django 4.1.5 on 2023-01-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productsapi", "0008_alter_orderitem_size_alter_product_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sex",
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
